2019-09-08 22:26:56 -0300: ended
2019-09-08 22:41:23 -0300: started
2019-09-08 22:41:25 -0300:  [*] Aguardando por abastecimentos
2019-09-08 22:41:25 -0300:  [x] Received {"valor":132.32,"bomba":125,"combustivel":"Gasolina"}
2019-09-08 22:41:25 -0300: Iniciando chamada a API...
2019-09-08 22:41:27 -0300: Conexão recusada com o servidor da API
2019-09-08 22:41:27 -0300: Iniciando chamada a API...
2019-09-08 22:41:29 -0300: Conexão recusada com o servidor da API
2019-09-08 22:41:29 -0300: Iniciando chamada a API...
2019-09-08 22:41:31 -0300: Conexão recusada com o servidor da API
2019-09-08 22:41:31 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:41:31 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:41:31 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:41:46 -0300: Iniciando chamada a API...
2019-09-08 22:41:48 -0300: Conexão recusada com o servidor da API
2019-09-08 22:41:48 -0300: Iniciando chamada a API...
2019-09-08 22:41:54 -0300: Resposta: <RestClient::Response 201 "{\"id\":539,\"...">
2019-09-08 22:41:54 -0300: Mensagem Processada!
2019-09-08 22:41:54 -0300:  [x] Received {"valor":13.96,"bomba":13,"combustivel":"Gasolina"}
2019-09-08 22:41:54 -0300: Iniciando chamada a API...
2019-09-08 22:41:55 -0300: Resposta: <RestClient::Response 201 "{\"id\":540,\"...">
2019-09-08 22:41:55 -0300: Mensagem Processada!
2019-09-08 22:41:55 -0300:  [x] Received {"valor":73.85,"bomba":146,"combustivel":"Etanol"}
2019-09-08 22:41:55 -0300: Iniciando chamada a API...
2019-09-08 22:41:56 -0300: Resposta: <RestClient::Response 201 "{\"id\":541,\"...">
2019-09-08 22:41:56 -0300: Mensagem Processada!
2019-09-08 22:41:56 -0300:  [x] Received {"valor":167.29,"bomba":198,"combustivel":"Gasolina"}
2019-09-08 22:41:56 -0300: Iniciando chamada a API...
2019-09-08 22:41:57 -0300: Resposta: <RestClient::Response 201 "{\"id\":542,\"...">
2019-09-08 22:41:57 -0300: Mensagem Processada!
2019-09-08 22:41:57 -0300:  [x] Received {"valor":198.94,"bomba":19,"combustivel":"Etanol"}
2019-09-08 22:41:57 -0300: Iniciando chamada a API...
2019-09-08 22:41:58 -0300: Resposta: <RestClient::Response 201 "{\"id\":543,\"...">
2019-09-08 22:41:58 -0300: Mensagem Processada!
2019-09-08 22:41:58 -0300:  [x] Received {"valor":233.91,"bomba":192,"combustivel":"Gasolina"}
2019-09-08 22:41:58 -0300: Iniciando chamada a API...
2019-09-08 22:41:59 -0300: Resposta: <RestClient::Response 201 "{\"id\":544,\"...">
2019-09-08 22:41:59 -0300: Mensagem Processada!
2019-09-08 22:41:59 -0300:  [x] Received {"valor":75.28,"bomba":107,"combustivel":"Gasolina"}
2019-09-08 22:41:59 -0300: Iniciando chamada a API...
2019-09-08 22:42:00 -0300: Resposta: <RestClient::Response 201 "{\"id\":545,\"...">
2019-09-08 22:42:00 -0300: Mensagem Processada!
2019-09-08 22:42:00 -0300:  [x] Received {"valor":35.91,"bomba":181,"combustivel":"Gasolina"}
2019-09-08 22:42:00 -0300: Iniciando chamada a API...
2019-09-08 22:42:02 -0300: Resposta: <RestClient::Response 201 "{\"id\":546,\"...">
2019-09-08 22:42:02 -0300: Mensagem Processada!
2019-09-08 22:42:02 -0300:  [x] Received {"valor":214.98,"bomba":54,"combustivel":"Gasolina"}
2019-09-08 22:42:02 -0300: Iniciando chamada a API...
2019-09-08 22:42:02 -0300: Errno::ECONNRESET
2019-09-08 22:42:02 -0300: An existing connection was forcibly closed by the remote host.
2019-09-08 22:42:02 -0300:  [x] Received {"valor":206.48,"bomba":44,"combustivel":"Gasolina"}
2019-09-08 22:42:02 -0300: Iniciando chamada a API...
2019-09-08 22:42:04 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:04 -0300: Iniciando chamada a API...
2019-09-08 22:42:06 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:06 -0300: Iniciando chamada a API...
2019-09-08 22:42:08 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:08 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:42:08 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:42:08 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:42:23 -0300: Iniciando chamada a API...
2019-09-08 22:42:25 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:25 -0300: Iniciando chamada a API...
2019-09-08 22:42:27 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:27 -0300: Iniciando chamada a API...
2019-09-08 22:42:29 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:29 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:42:29 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:42:29 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:42:44 -0300: Iniciando chamada a API...
2019-09-08 22:42:46 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:46 -0300: Iniciando chamada a API...
2019-09-08 22:42:48 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:48 -0300: Iniciando chamada a API...
2019-09-08 22:42:50 -0300: Conexão recusada com o servidor da API
2019-09-08 22:42:50 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:42:50 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:42:50 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:43:05 -0300: Iniciando chamada a API...
2019-09-08 22:43:07 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:07 -0300: Iniciando chamada a API...
2019-09-08 22:43:09 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:09 -0300: Iniciando chamada a API...
2019-09-08 22:43:11 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:11 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:43:11 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:43:11 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:43:26 -0300: Iniciando chamada a API...
2019-09-08 22:43:28 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:28 -0300: Iniciando chamada a API...
2019-09-08 22:43:30 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:30 -0300: Iniciando chamada a API...
2019-09-08 22:43:32 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:32 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:43:32 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:43:32 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:43:47 -0300: Iniciando chamada a API...
2019-09-08 22:43:49 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:49 -0300: Iniciando chamada a API...
2019-09-08 22:43:51 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:51 -0300: Iniciando chamada a API...
2019-09-08 22:43:53 -0300: Conexão recusada com o servidor da API
2019-09-08 22:43:53 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:43:53 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:43:53 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:44:08 -0300: Iniciando chamada a API...
2019-09-08 22:44:10 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:10 -0300: Iniciando chamada a API...
2019-09-08 22:44:12 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:12 -0300: Iniciando chamada a API...
2019-09-08 22:44:14 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:14 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:44:14 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:44:14 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:44:29 -0300: Iniciando chamada a API...
2019-09-08 22:44:31 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:31 -0300: Iniciando chamada a API...
2019-09-08 22:44:33 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:33 -0300: Iniciando chamada a API...
2019-09-08 22:44:35 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:35 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:44:35 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:44:35 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:44:50 -0300: Iniciando chamada a API...
2019-09-08 22:44:52 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:52 -0300: Iniciando chamada a API...
2019-09-08 22:44:54 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:54 -0300: Iniciando chamada a API...
2019-09-08 22:44:56 -0300: Conexão recusada com o servidor da API
2019-09-08 22:44:56 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:44:56 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:44:56 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:45:11 -0300: Iniciando chamada a API...
2019-09-08 22:45:13 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:13 -0300: Iniciando chamada a API...
2019-09-08 22:45:15 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:15 -0300: Iniciando chamada a API...
2019-09-08 22:45:17 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:17 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:45:17 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:45:17 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:45:32 -0300: Iniciando chamada a API...
2019-09-08 22:45:34 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:34 -0300: Iniciando chamada a API...
2019-09-08 22:45:36 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:36 -0300: Iniciando chamada a API...
2019-09-08 22:45:38 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:38 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:45:38 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:45:38 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:45:53 -0300: Iniciando chamada a API...
2019-09-08 22:45:55 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:55 -0300: Iniciando chamada a API...
2019-09-08 22:45:57 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:57 -0300: Iniciando chamada a API...
2019-09-08 22:45:59 -0300: Conexão recusada com o servidor da API
2019-09-08 22:45:59 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:45:59 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:45:59 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:46:14 -0300: Iniciando chamada a API...
2019-09-08 22:46:16 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:16 -0300: Iniciando chamada a API...
2019-09-08 22:46:18 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:18 -0300: Iniciando chamada a API...
2019-09-08 22:46:20 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:20 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:46:20 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:46:20 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:46:35 -0300: Iniciando chamada a API...
2019-09-08 22:46:37 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:37 -0300: Iniciando chamada a API...
2019-09-08 22:46:39 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:39 -0300: Iniciando chamada a API...
2019-09-08 22:46:41 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:41 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:46:41 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:46:41 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:46:56 -0300: Iniciando chamada a API...
2019-09-08 22:46:58 -0300: Conexão recusada com o servidor da API
2019-09-08 22:46:58 -0300: Iniciando chamada a API...
2019-09-08 22:47:00 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:00 -0300: Iniciando chamada a API...
2019-09-08 22:47:02 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:02 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:47:02 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:47:02 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:47:17 -0300: Iniciando chamada a API...
2019-09-08 22:47:19 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:19 -0300: Iniciando chamada a API...
2019-09-08 22:47:21 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:21 -0300: Iniciando chamada a API...
2019-09-08 22:47:23 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:23 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:47:23 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:47:23 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:47:38 -0300: Iniciando chamada a API...
2019-09-08 22:47:40 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:40 -0300: Iniciando chamada a API...
2019-09-08 22:47:42 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:42 -0300: Iniciando chamada a API...
2019-09-08 22:47:44 -0300: Conexão recusada com o servidor da API
2019-09-08 22:47:44 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:47:44 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:47:44 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:47:59 -0300: Iniciando chamada a API...
2019-09-08 22:48:01 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:01 -0300: Iniciando chamada a API...
2019-09-08 22:48:03 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:03 -0300: Iniciando chamada a API...
2019-09-08 22:48:05 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:05 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:48:05 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:48:05 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:48:20 -0300: Iniciando chamada a API...
2019-09-08 22:48:22 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:22 -0300: Iniciando chamada a API...
2019-09-08 22:48:24 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:24 -0300: Iniciando chamada a API...
2019-09-08 22:48:26 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:26 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:48:26 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:48:26 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:48:41 -0300: Iniciando chamada a API...
2019-09-08 22:48:43 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:43 -0300: Iniciando chamada a API...
2019-09-08 22:48:45 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:45 -0300: Iniciando chamada a API...
2019-09-08 22:48:47 -0300: Conexão recusada com o servidor da API
2019-09-08 22:48:47 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:48:47 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:48:47 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:49:02 -0300: Iniciando chamada a API...
2019-09-08 22:49:04 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:04 -0300: Iniciando chamada a API...
2019-09-08 22:49:06 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:06 -0300: Iniciando chamada a API...
2019-09-08 22:49:08 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:08 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:49:08 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:49:08 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:49:23 -0300: Iniciando chamada a API...
2019-09-08 22:49:25 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:25 -0300: Iniciando chamada a API...
2019-09-08 22:49:27 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:27 -0300: Iniciando chamada a API...
2019-09-08 22:49:29 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:29 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:49:29 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:49:29 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:49:44 -0300: Iniciando chamada a API...
2019-09-08 22:49:46 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:46 -0300: Iniciando chamada a API...
2019-09-08 22:49:48 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:48 -0300: Iniciando chamada a API...
2019-09-08 22:49:50 -0300: Conexão recusada com o servidor da API
2019-09-08 22:49:50 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:49:50 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:49:50 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:50:05 -0300: Iniciando chamada a API...
2019-09-08 22:50:07 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:07 -0300: Iniciando chamada a API...
2019-09-08 22:50:09 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:09 -0300: Iniciando chamada a API...
2019-09-08 22:50:11 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:11 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:50:11 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:50:11 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:50:26 -0300: Iniciando chamada a API...
2019-09-08 22:50:28 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:28 -0300: Iniciando chamada a API...
2019-09-08 22:50:30 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:30 -0300: Iniciando chamada a API...
2019-09-08 22:50:32 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:32 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:50:32 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:50:32 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:50:47 -0300: Iniciando chamada a API...
2019-09-08 22:50:49 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:49 -0300: Iniciando chamada a API...
2019-09-08 22:50:51 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:51 -0300: Iniciando chamada a API...
2019-09-08 22:50:53 -0300: Conexão recusada com o servidor da API
2019-09-08 22:50:53 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:50:53 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:50:53 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:51:08 -0300: Iniciando chamada a API...
2019-09-08 22:51:10 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:10 -0300: Iniciando chamada a API...
2019-09-08 22:51:12 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:12 -0300: Iniciando chamada a API...
2019-09-08 22:51:14 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:14 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:51:14 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:51:14 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:51:29 -0300: Iniciando chamada a API...
2019-09-08 22:51:31 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:31 -0300: Iniciando chamada a API...
2019-09-08 22:51:33 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:33 -0300: Iniciando chamada a API...
2019-09-08 22:51:35 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:35 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:51:35 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:51:35 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:51:50 -0300: Iniciando chamada a API...
2019-09-08 22:51:52 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:52 -0300: Iniciando chamada a API...
2019-09-08 22:51:54 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:54 -0300: Iniciando chamada a API...
2019-09-08 22:51:56 -0300: Conexão recusada com o servidor da API
2019-09-08 22:51:56 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:51:56 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:51:56 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:52:11 -0300: Iniciando chamada a API...
2019-09-08 22:52:13 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:13 -0300: Iniciando chamada a API...
2019-09-08 22:52:15 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:15 -0300: Iniciando chamada a API...
2019-09-08 22:52:17 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:17 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:52:17 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:52:17 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:52:32 -0300: Iniciando chamada a API...
2019-09-08 22:52:34 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:34 -0300: Iniciando chamada a API...
2019-09-08 22:52:36 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:36 -0300: Iniciando chamada a API...
2019-09-08 22:52:38 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:38 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:52:38 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:52:38 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:52:53 -0300: Iniciando chamada a API...
2019-09-08 22:52:55 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:55 -0300: Iniciando chamada a API...
2019-09-08 22:52:57 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:57 -0300: Iniciando chamada a API...
2019-09-08 22:52:59 -0300: Conexão recusada com o servidor da API
2019-09-08 22:52:59 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:52:59 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:52:59 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:53:14 -0300: Iniciando chamada a API...
2019-09-08 22:53:16 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:16 -0300: Iniciando chamada a API...
2019-09-08 22:53:18 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:18 -0300: Iniciando chamada a API...
2019-09-08 22:53:20 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:20 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:53:20 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:53:20 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:53:35 -0300: Iniciando chamada a API...
2019-09-08 22:53:37 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:37 -0300: Iniciando chamada a API...
2019-09-08 22:53:39 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:39 -0300: Iniciando chamada a API...
2019-09-08 22:53:41 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:41 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:53:41 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:53:41 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:53:56 -0300: Iniciando chamada a API...
2019-09-08 22:53:58 -0300: Conexão recusada com o servidor da API
2019-09-08 22:53:58 -0300: Iniciando chamada a API...
2019-09-08 22:54:00 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:00 -0300: Iniciando chamada a API...
2019-09-08 22:54:02 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:02 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:54:02 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:54:02 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:54:17 -0300: Iniciando chamada a API...
2019-09-08 22:54:19 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:19 -0300: Iniciando chamada a API...
2019-09-08 22:54:21 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:21 -0300: Iniciando chamada a API...
2019-09-08 22:54:23 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:23 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:54:23 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:54:23 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:54:38 -0300: Iniciando chamada a API...
2019-09-08 22:54:40 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:40 -0300: Iniciando chamada a API...
2019-09-08 22:54:42 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:42 -0300: Iniciando chamada a API...
2019-09-08 22:54:44 -0300: Conexão recusada com o servidor da API
2019-09-08 22:54:44 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:54:44 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:54:44 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:54:59 -0300: Iniciando chamada a API...
2019-09-08 22:55:01 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:01 -0300: Iniciando chamada a API...
2019-09-08 22:55:03 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:03 -0300: Iniciando chamada a API...
2019-09-08 22:55:05 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:05 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:55:05 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:55:05 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:55:20 -0300: Iniciando chamada a API...
2019-09-08 22:55:22 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:22 -0300: Iniciando chamada a API...
2019-09-08 22:55:24 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:24 -0300: Iniciando chamada a API...
2019-09-08 22:55:26 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:26 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:55:26 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:55:26 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:55:41 -0300: Iniciando chamada a API...
2019-09-08 22:55:43 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:43 -0300: Iniciando chamada a API...
2019-09-08 22:55:45 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:45 -0300: Iniciando chamada a API...
2019-09-08 22:55:47 -0300: Conexão recusada com o servidor da API
2019-09-08 22:55:47 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:55:47 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:55:47 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:56:02 -0300: Iniciando chamada a API...
2019-09-08 22:56:04 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:04 -0300: Iniciando chamada a API...
2019-09-08 22:56:06 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:06 -0300: Iniciando chamada a API...
2019-09-08 22:56:08 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:08 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:56:08 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:56:08 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:56:23 -0300: Iniciando chamada a API...
2019-09-08 22:56:25 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:25 -0300: Iniciando chamada a API...
2019-09-08 22:56:27 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:27 -0300: Iniciando chamada a API...
2019-09-08 22:56:29 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:29 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:56:29 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:56:29 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:56:44 -0300: Iniciando chamada a API...
2019-09-08 22:56:46 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:46 -0300: Iniciando chamada a API...
2019-09-08 22:56:48 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:48 -0300: Iniciando chamada a API...
2019-09-08 22:56:50 -0300: Conexão recusada com o servidor da API
2019-09-08 22:56:50 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:56:50 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:56:50 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:57:05 -0300: Iniciando chamada a API...
2019-09-08 22:57:07 -0300: Conexão recusada com o servidor da API
2019-09-08 22:57:07 -0300: Iniciando chamada a API...
2019-09-08 22:57:09 -0300: Conexão recusada com o servidor da API
2019-09-08 22:57:09 -0300: Iniciando chamada a API...
2019-09-08 22:57:11 -0300: Conexão recusada com o servidor da API
2019-09-08 22:57:11 -0300: Após 3 tentativas não foi possível efetuar conexão.
2019-09-08 22:57:11 -0300: O erro retornado foi: Failed to open TCP connection to localhost:3000 (No connection could be made because the target machine actively refused it. - connect(2) for "localhost" port 3000)
2019-09-08 22:57:11 -0300: Tentando reconexão com o servidor em 15 segundos...
2019-09-08 22:57:26 -0300: Iniciando chamada a API...
2019-09-08 22:57:26 -0300: ended
